---
- name: Play for building docker image and running container from it
  hosts: localhost
  gather_facts: false

  vars_files:
    - variables.yaml
    - secrets.yaml

  tasks:
    - name: Create Working directory
      ansible.builtin.file:
        path: "{{ working_directory }}"
        state: directory
        mode: "0755"

    - name: Checkout code
      ansible.builtin.git:
        repo: https://github.com/andonyan/devops-programme.git
        dest: "{{ working_directory }}"
        version: "{{ branch_name }}"
        force: true

    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"

    - name: Build Docker Image & Push to Docker Hub
      community.docker.docker_image:
        build:
          path: "{{ working_directory }}"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        push: true

    - name: Run App Container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        env:
          PORT: "{{ listen_port | int }}"
        ports:
          - "{{ expose_port }}:{{ listen_port }}"
